# GitHub Pages Configuration for SimBench

# This file tells GitHub Pages how to build the site
# Place this in the root of your repository

# Theme (optional, can be removed for custom HTML)
theme: jekyll-theme-minimal

# Title and description
title: SimBench
description: The First Large-Scale Benchmark for Simulating Human Behavior with LLMs

# Exclude files from the build
exclude:
  - README.md
  - convert_results_to_json.py
  - "*.pkl"
  - "*.py"
  - node_modules/
  - .git/
  - .gitignore

# Include files
include:
  - website/

# Plugins (if needed)
plugins:
  - jekyll-relative-links

# Relative links
relative_links:
  enabled: true
  collections: true
